# Generated by Django 3.2.4 on 2021-06-24 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_auto_20210624_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of comment'),
        ),
    ]
